services:
  soabus:
    image: jrgiadach/soabus:v1
    platform: linux/amd64
    ports:
      - "5001:5000"
    container_name: asai

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
